name: tracktion
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 0.21.0-nullsafety.0
  flutter_bloc: 7.0.0-nullsafety.6
  http: ^0.13.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.5
  connectivity: ^3.0.2
  # moor: ^3.0.0
  moor: ^4.0.0-nullsafety.1
  path_provider: ^2.0.1
  moor_flutter: ^4.0.0-nullsafety
  fl_chart: ^0.20.1
  font_awesome_flutter: ^9.0.0-nullsafety
  modal_bottom_sheet: ^2.0.0-nullsafety.1
  flutter_clean_calendar: ^1.0.2+1 # pending
  flutter_cupertino_date_picker: # pending
    git:
      url: https://github.com/imshashank/flutter-cupertino-date-picker # Repo
      ref: master

  path: ^1.6.4
  undo: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # moor_generator: ^3.4.1
  build_runner: ^1.10.7

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/home.svg
    - assets/vectors/abs.svg
    - assets/vectors/back.svg
    - assets/vectors/butt.svg
    - assets/vectors/calfs.svg
    - assets/vectors/chest.svg
    - assets/vectors/hamstrings.svg
    - assets/vectors/legs.svg
    - assets/vectors/quads.svg
    - assets/vectors/shoulders.svg
    - assets/vectors/arms.svg
    - assets/vectors/routines/1.svg
    - assets/vectors/routines/2.svg
    - assets/vectors/routines/3.svg
    - assets/vectors/routines/4.svg
    - assets/vectors/routines/5.svg
    - assets/vectors/routines/6.svg

  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
